version: '{build}'
os: Visual Studio 2017
configuration: Debug
skip_branch_with_pr: true
install:
- appveyor version
build_script:
- ps: ./Build.ps1
artifacts:
#  - path: 'src\**\*.nupkg'
#    name: NuGet Packages
  - path: 'src\**\*.snupkg'
    name: NuGet Symbol Packages
deploy:
  provider: NuGet
  api_key:
    secure: ULNYOwHh7D9RXmLaWXHSG/NYpP4URFOHBoO6whe3TBC4ckSt6rVP3y9/q4lvQfQb
